create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  paid_at timestamptz,
  unlock_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.sponsor_proofs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  memo text,
  image_base64 text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.profiles enable row level security;
alter table public.sponsor_proofs enable row level security;

create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create policy "proofs_insert_own"
on public.sponsor_proofs
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "proofs_select_own"
on public.sponsor_proofs
for select
to authenticated
using (auth.uid() = user_id);
